---
title: "Cleaning data"
author: "Susi"
date: "2026-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load / install required packages

load_pkg <- function(pkg){
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
  }
}

# Load required packages
load_pkg("readxl")
load_pkg("dplyr")
load_pkg("ggplot2")
load_pkg("tidyr")
load_pkg("janitor")
load_pkg("here")


```

## Import data

```{r}

data <- read_excel(here("raw data/combined_10March_2026.xlsx"))
str(data)

```
## Fixing column names

```{r}

data <- data %>% clean_names()
names(data)

```

```{r}

# Structure 
str(data)

# Converting inconsistent "N/A" and "-" strings to NA
data <- data %>% mutate(across(everything(), ~ ifelse(. %in% c("N/A", "-", ""), NA, .)))

# checking for duplicate rows
sum(duplicated(data)) # 2 not so bad, probably happended when copying over. remove:
data <- data %>% distinct()

# as per structure, many variable are character but should be either numeric or factors
# converting to factors:
  
factor_vars <- c("individual_id", "sex", "age", "origin", "strain", "condition", "trial_day", "background_colour", "housing_s", "housing_social")

data <- data %>%
  mutate(across(all_of(factor_vars), as.factor))

# converting to numeric:
  
number_vars <- c( "latency_swim_freely", "timespent_contact" ,"timespent_active", "nb_dart_startle", "distance_no","latency_approach_no", "latency_touch_no", "luminosity", "photoperiod", "salinity")

data <- data %>%
  mutate(across(all_of(number_vars), as.numeric))


summary(data)

```

```{r}

data %>% count(study_species) %>%
  ggplot(aes(x = study_species, y = n, fill= study_species)) +
  geom_col() +
  labs(title="Count by Species", x="Species", y="Count")

```

